REG-6 champion portal journey
thebiggive/regression-tests pull request #44
Opened 2021-01-14 12:14 UTC by tbg-jasonfung

- Update readme for users setting up this repo for the first time
- REG-6 support allocating funds champion portal journey
- Update env file

2021-01-14 12:16 UTC, tbg-jasonfung commented
@NoelLH I've tried this out on IE11 and it's already tripping up on finding and clicking on the nav menu item, I don't think we should spend so much time trying to get this working on IE11, especially when SF has [stopped extended support](https://help.salesforce.com/articleView?id=000333934&type=1&mode=1) for this browser with LEX

2021-01-14 13:26 UTC, NoelLH requested changes
Looks like a good start. I think the vars need configuring in CI, and there's a few things to address inline.

2021-01-14 13:26 UTC, NoelLH commented on features/champion-offer.feature
> +    Then I would like to de-allocate the funding
This last line doesn't really explain the steps or outcome as BDD should. Are we actually doing a thing? What happens as a result to indicate that it worked?

Should also ideally keep end of file newlines outside SF contexts for clean diffs

2021-01-14 13:26 UTC, NoelLH commented on pages/ChampionPortalLoginPage.js
> +        this.browser.pause(500);
Do we really need all these pauses? These should be individually tested and explained in specific terms to ensure we're not making tests slower or more brittle than they need to be. Most existing helpers know how to wait for an element to be interactable automatically.

This one is especially suspect as it happens _after_ the relevant check. Why is it in this method?

2021-01-14 13:26 UTC, NoelLH commented on pages/ChampionPortalLoginPage.js
> +    clickNavItem() {
Name the method with what it does more specifically as it's not parameterised?

2021-01-14 13:26 UTC, NoelLH commented on pages/ChampionPortalLoginPage.js
> +        clickSelector("//td[@class='slds-color__background_gray-5']//lightning-primitive-cell-factory//span/button");
How do we know which row? If this only works on the assumption there is exactly 1 campaign, make this dependency explicit in the test.

2021-01-14 13:26 UTC, NoelLH commented on pages/ChampionPortalLoginPage.js
> +        checkSelectorContent(
These two feel pretty risky. What if we change the table styles? Seems like we should be doing an actual check that we are in the expected part of the page, e.g. based on a heading.

2021-01-14 13:26 UTC, NoelLH commented on pages/ChampionPortalLoginPage.js
> +    checkListOfCharities() {
As above

2021-01-14 13:26 UTC, NoelLH commented on pages/ChampionPortalLoginPage.js
> +     * switchToParentFrame() and elementSendKeys() doesn't seem to unfocus correctly
There is no frame involved so the parent frame call will do nothing. This doesn't explain why we need a pre-click before the save button click.

2021-01-14 13:26 UTC, NoelLH commented on pages/ChampionPortalLoginPage.js
> +        this.checkSaveButton();
This is redundant as the Xpath selector used on the next line already checks that what it's clicking says _Save_

2021-01-14 13:26 UTC, NoelLH commented on pages/ChampionPortalLoginPage.js
> +     * Reset funding
Bit more description?

2021-01-14 13:26 UTC, NoelLH commented on pages/ChampionPortalLoginPage.js
> +export default class ChampionPortalLoginPage {
Class name and comment do not match the actual scope.

2021-01-14 13:29 UTC, NoelLH commented on README.md
> +Make sure you have latest Yarn and Node installed and follow the detailed instructions for your OS [here](https://github.com/nodejs/node-gyp)
What required `node-gyp` @tbg-jasonfung? I don't have it and have had no issues.

2021-01-14 15:20 UTC, tbg-jasonfung commented on README.md
> +Make sure you have latest Yarn and Node installed and follow the detailed instructions for your OS [here](https://github.com/nodejs/node-gyp)
@NoelLH interesting, when I ran the test locally, the error message was pointing me to this link and I followed the instructions and got it set up eventually

2021-01-14 15:44 UTC, NoelLH requested changes
Couple more things inline. The test is also still failing?

2021-01-14 15:44 UTC, NoelLH commented on pages/ChampionPortalAllocateFunds.js
> +            'Match funding campaigns'
@tbg-jasonfung I meant that these checks should validate that the correct campaign is in the correct table, not just that the table exists!

2021-01-14 15:44 UTC, NoelLH commented on pages/ChampionPortalAllocateFunds.js
> +            "//div[@class='uiOutputRichText']//h1",
As above

2021-01-14 15:44 UTC, NoelLH commented on pages/ChampionPortalAllocateFunds.js
> +     * this ensures the 'handleOnCellChange' event is triggered after the checkbox has been selected
Isn't this a bit of a usability issue and a potential bug in the actual form, if champions have to do the equivalent of this click? If our tests break because there's a race condition when you click Save directly, then the actual form can too.

2021-01-14 16:05 UTC, tbg-jasonfung commented on pages/ChampionPortalAllocateFunds.js
> +     * this ensures the 'handleOnCellChange' event is triggered after the checkbox has been selected
@NoelLH I don't think so, its pretty obvious you have to click away as a mini modal pops up, also this is using the native edit feature within `lightning-datatable`

2021-01-14 16:05 UTC, tbg-jasonfung commented
> Couple more things inline. The test is also still failing?

@NoelLH Not really sure why its failing, its passing locally for me, any ideas?

2021-01-14 17:23 UTC, NoelLH commented on README.md
> +Make sure you have latest Yarn and Node installed and follow the detailed instructions for your OS [here](https://github.com/nodejs/node-gyp)
@tbg-jasonfung seems odd. Could we update the note to at least suggest this may be platform specific, if you don't know where that message came from?

2021-01-14 17:32 UTC, NoelLH requested changes

2021-01-14 17:32 UTC, NoelLH commented on pages/ChampionPortalAllocateFunds.js
> +        goToUrl(campaignsPage);
This is less like user behaviour than the click. Should be able to avoid jumping URL mid-journey?

2021-01-14 17:32 UTC, NoelLH commented on pages/ChampionPortalAllocateFunds.js
> +     * this ensures the 'handleOnCellChange' event is triggered after the checkbox has been selected
OK, haven't seen the modal in action. Could the comment reflect this more clearly so other devs in the same position understand what's going on?

2021-01-14 17:32 UTC, NoelLH commented on pages/ChampionPortalAllocateFunds.js
> +            "//td[@data-label = 'Title']//lightning-primitive-cell-factory//span//div//lightning-base-formatted-text",
Does the table itself not have an overall title? How do champions distinguish them at a glance? If it's by one having the title "Campaign Title" while the other is "Title" then this seems like not the best UX – and also something that we are highly likely to change in the future, breaking this test's assumptions.

This is also now getting _very_ deep into CSS class dependencies that will likely break when SF roll out any Communities design changes.

What I think we should be aiming for is to both:
1. check we are in the right table – by reading its title like a champion does, and only using Xpath to help mirror that type of parsing rather than to go into really Communities implementation specific stuff like this line; and
2. check the right campaign appears in that table

2021-01-15 09:19 UTC, tbg-jasonfung commented on pages/ChampionPortalAllocateFunds.js
> +            "//td[@data-label = 'Title']//lightning-primitive-cell-factory//span//div//lightning-base-formatted-text",
@NoelLH I don't think I follow, when we get to checking the list of charities, there is only 1 data table present?

r.e the deep CSS stuff, its quite difficult to pinpoint where the exact copy lives, because it's auto wrapping the formatted text with `<span>` `<div>`

2021-01-15 10:14 UTC, NoelLH commented on pages/ChampionPortalAllocateFunds.js
> +            "//td[@data-label = 'Title']//lightning-primitive-cell-factory//span//div//lightning-base-formatted-text",
OK, just had a look at the video of the interface and I think the scope of the check is good.

Re avoiding custom markup ties, you can also use Xpath in Chrome dev tools etc. to test things like text matching and traversal from matched elements more quickly which I found useful. But actually as this one relies mostly on pseudo-elements themselves and not their classes hopefully it won't break too often.

2021-01-15 10:15 UTC, NoelLH approved these changes

2021-01-15 10:15 UTC, merged